name: MouseDef
options:
  usesTabs: false
  indentWidth: 2
  tabWidth: 2
  deploymentTarget:
    macOS: "10.15"
  configFiles:
    Debug: Xcodegen/Debug.xcconfig
    Release: Xcodegen/Release.xcconfig
include:
  - path: XcodeGen/MouseDef.yml
    relativePaths: false
fileGroups:
  - .env
  - .gitignore
  - README.md
  - Scripts
  - XcodeGen
  - build_pipeline.sh
  - project.yml
